#!/usr/bin/env bash
# Resolve WHICH CONFIG LANGUAGE this machine's Hyprland actually reads, and the
# Hyprland version range that language is valid for.
#
# Since Hyprland 0.55 hyprlang is deprecated in favour of lua, and a
# `hyprland.lua` sitting in the config dir is loaded INSTEAD of `hyprland.conf`.
# So "which language do we emit" is a version cliff like every other cliff in
# `references/_shared/version-matrix.md` - and it is NOT guessable. When the
# version cannot be detected this script refuses to pick one and asks the caller.
#
# Usage:
#   config-language.sh                    resolve from $HYPR_VERSION or detect-version.sh
#   config-language.sh --language lua     force the language (the explicit choice)
#   config-language.sh --version 0.56.2   resolve from a version, skipping detection
#   config-language.sh --range <lang>     print only that language's version range
#
# Env:
#   HYPR_VERSION       use this version instead of running detect-version.sh
#                      (x.y[.z], or the literal `unknown`)
#   HYPR_CONFIG_LANG   the explicit choice (lua|hyprlang); same as --language
#
# Output (KEY=value lines, the convention every script here follows):
#   HYPR_VERSION=<x.y.z|unknown>
#   CONFIG_LANGUAGE=<lua|hyprlang>
#   CONFIG_LANGUAGE_SOURCE=<detected|explicit>
#   CONFIG_FILE=<hyprland.lua|hyprland.conf>
#   CONFIG_LANGUAGE_RANGE=<the Hyprland versions that language is valid for>
#
# When the version cannot be detected AND no explicit choice was supplied, it
# reports what it can emit and stops instead of assuming:
#   CONFIG_LANGUAGE=undecided
#   EMITTABLE_LANGUAGES=lua hyprlang
#   LANGUAGE_OPTION=lua <range>
#   LANGUAGE_OPTION=hyprlang <range>
#   ERROR: ... requires an explicit choice ...
#
# Exit: 0 resolved, 2 bad usage, 3 undetected version and no explicit choice.
#
# Sourcing this file defines the helpers WITHOUT running the CLI, so the other
# scripts share one definition of the cliff, the file names and the ranges.

# The cliff: 0.55 is where the documented config language becomes lua.
CONFIG_LANG_CLIFF="0.55"

# `config_lang_range <lua|hyprlang>` - the Hyprland versions that language is
# valid for. The hyprlang window is the one the project published
# (<https://hypr.land/news/26_lua/>): "supported for 1 - 2 releases starting
# from 0.55. After that, hyprlang will be dropped."
config_lang_range() {
    case "${1:-}" in
        lua)      printf 'Hyprland %s and newer (lua is the documented config language since %s)\n' \
                      "$CONFIG_LANG_CLIFF" "$CONFIG_LANG_CLIFF" ;;
        hyprlang) printf 'Hyprland up to 0.54; deprecated since %s and supported for 1 - 2 releases starting from %s, after which hyprlang is dropped\n' \
                      "$CONFIG_LANG_CLIFF" "$CONFIG_LANG_CLIFF" ;;
        *)        return 1 ;;
    esac
}

# `config_lang_file <lang>` - the main config file name for that language.
config_lang_file() {
    case "${1:-}" in
        lua)      printf 'hyprland.lua\n' ;;
        hyprlang) printf 'hyprland.conf\n' ;;
        *)        return 1 ;;
    esac
}

# `config_lang_comment <lang>` - that language's line-comment marker.
config_lang_comment() {
    case "${1:-}" in
        lua)      printf -- '--\n' ;;
        hyprlang) printf '#\n' ;;
        *)        return 1 ;;
    esac
}

# `config_lang_of_file <path-or-name>` - the language a config file is written in.
config_lang_of_file() {
    case "${1:-}" in
        *.lua)  printf 'lua\n' ;;
        *.conf) printf 'hyprlang\n' ;;
        *)      return 1 ;;
    esac
}

# `config_lang_provenance <lang>` - the header every generated config carries, so
# a user reading it on their own machine can tell what it is and what it is good
# for. Comment-prefixed for the target language.
config_lang_provenance() {
    local lang="${1:-}" c range
    c="$(config_lang_comment "$lang")" || return 1
    range="$(config_lang_range "$lang")" || return 1
    printf '%s Generated by the hyprland-config plugin.\n' "$c"
    printf '%s CONFIG_LANGUAGE=%s\n' "$c" "$lang"
    printf '%s CONFIG_LANGUAGE_RANGE=%s\n' "$c" "$range"
}

# `config_lang_present <path>` - is a config file THERE, for shadowing purposes?
# `-e` alone is not enough: a DANGLING symlink (what stow/chezmoi leave when the
# dotfiles tree is not checked out yet) fails `-e` while still occupying the name
# Hyprland looks up and the name a write would have to clobber. Treat the name as
# taken whenever anything holds it.
config_lang_present() {
    [ -e "${1:-}" ] || [ -L "${1:-}" ]
}

# `config_lang_for_version <version>` - lua | hyprlang | unknown.
# lua-language version   = 0.55 or higher (or any 1.x+)
# hyprlang-language version = below 0.55
config_lang_for_version() {
    local v="${1:-}" major minor
    case "$v" in
        ""|unknown|UNKNOWN) printf 'unknown\n'; return 0 ;;
    esac
    v="${v#v}"
    major="${v%%.*}"
    if [ "$major" = "$v" ]; then minor="0"; else minor="${v#*.}"; minor="${minor%%.*}"; fi
    case "$major" in ''|*[!0-9]*) printf 'unknown\n'; return 0 ;; esac
    case "$minor" in ''|*[!0-9]*) printf 'unknown\n'; return 0 ;; esac
    if [ "$major" -ge 1 ] || { [ "$major" -eq 0 ] && [ "$minor" -ge 55 ]; }; then
        printf 'lua\n'
    else
        printf 'hyprlang\n'
    fi
}

# `config_lang_report_undecided` - AC-5's report: what we CAN emit, and that a
# choice is required. Printed to stdout so the caller can relay it verbatim.
config_lang_report_undecided() {
    printf 'CONFIG_LANGUAGE=undecided\n'
    printf 'EMITTABLE_LANGUAGES=lua hyprlang\n'
    printf 'LANGUAGE_OPTION=lua %s\n' "$(config_lang_range lua)"
    printf 'LANGUAGE_OPTION=hyprlang %s\n' "$(config_lang_range hyprlang)"
    printf 'ERROR: the installed Hyprland version could not be detected, so the config language cannot be chosen for you. This step requires an explicit choice: re-run with HYPR_CONFIG_LANG=lua or HYPR_CONFIG_LANG=hyprlang (or --language <lua|hyprlang>).\n'
}

# `config_lang_resolve` - the whole decision. Reads HYPR_CONFIG_LANG (explicit
# choice) and HYPR_VERSION (detected), running detect-version.sh only when
# HYPR_VERSION is unset. Prints the KEY=value block. Exit 3 when undecided.
config_lang_resolve() {
    local here version lang choice
    here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    choice="${HYPR_CONFIG_LANG:-}"

    if [ -n "$choice" ]; then
        case "$choice" in
            lua|hyprlang) ;;
            *) printf 'ERROR: HYPR_CONFIG_LANG must be `lua` or `hyprlang`, got: %s\n' "$choice" >&2
               return 2 ;;
        esac
    fi

    if [ -n "${HYPR_VERSION:-}" ]; then
        version="$HYPR_VERSION"
    elif [ -x "$here/detect-version.sh" ] || [ -f "$here/detect-version.sh" ]; then
        version="$(bash "$here/detect-version.sh" 2>/dev/null | sed -n 's/^HYPR_VERSION=//p' | head -n1)"
        [ -n "$version" ] || version="unknown"
    else
        version="unknown"
    fi

    printf 'HYPR_VERSION=%s\n' "$version"

    if [ -n "$choice" ]; then
        lang="$choice"
        printf 'CONFIG_LANGUAGE=%s\n' "$lang"
        printf 'CONFIG_LANGUAGE_SOURCE=explicit\n'
    else
        lang="$(config_lang_for_version "$version")"
        if [ "$lang" = "unknown" ]; then
            config_lang_report_undecided
            return 3
        fi
        printf 'CONFIG_LANGUAGE=%s\n' "$lang"
        printf 'CONFIG_LANGUAGE_SOURCE=detected\n'
    fi
    printf 'CONFIG_FILE=%s\n' "$(config_lang_file "$lang")"
    printf 'CONFIG_LANGUAGE_RANGE=%s\n' "$(config_lang_range "$lang")"
}

config_lang_main() {
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --language)
                [ "$#" -ge 2 ] || { echo "ERROR: --language needs a value" >&2; return 2; }
                HYPR_CONFIG_LANG="$2"; shift 2 ;;
            --version)
                [ "$#" -ge 2 ] || { echo "ERROR: --version needs a value" >&2; return 2; }
                HYPR_VERSION="$2"; shift 2 ;;
            --range)
                [ "$#" -ge 2 ] || { echo "ERROR: --range needs a language" >&2; return 2; }
                config_lang_range "$2" || { echo "ERROR: unknown language: $2" >&2; return 2; }
                return 0 ;;
            -h|--help)
                sed -n '2,40p' "${BASH_SOURCE[0]}"; return 0 ;;
            *)
                echo "ERROR: unknown argument: $1" >&2; return 2 ;;
        esac
    done
    export HYPR_CONFIG_LANG HYPR_VERSION
    config_lang_resolve
}

# Run the CLI only when executed, not when sourced.
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    set -uo pipefail
    config_lang_main "$@"
    exit $?
fi
