#!/usr/bin/env bash
# S0018-hyprland-config-lua-4 - refuter probe F2: hunt a false success.
#
# AC-1: "IF the Hyprland config directory already contains a hyprland.lua THEN
#        THE SYSTEM SHALL NOT install a hyprlang .conf and SHALL report that the
#        lua config takes precedence over it"
#
# The spec's Objective names the exact failure to close: "a SAFE_APPLY=ok printed
# for a change that the compositor never read". So this probe drives the WHOLE
# apply path (safe-apply.sh -> install-config.sh) and every shadow shape it can
# reach, asserting that none of them ends in an ok/DONE line.
#
# Run: bash tests/regress_0018_F2.sh
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
RS="$ROOT/skills/rice/scripts"

tmp="$(mktemp -d /tmp/regress0018F2.XXXXXX)"
stage="$tmp/stage-conf"
HYPR_CONFIG_LANG=hyprlang HYPR_VERSION=0.54.3 bash "$RS/emit-config.sh" "$stage" >/dev/null 2>&1

fails=0
ok()   { echo "PASS  $1"; }
bad()  { echo "FAIL  $1"; echo "$2" | sed 's/^/      /'; fails=$((fails + 1)); }

# `no_success <label> <output> <rc>` - a refusal must be non-zero and must carry
# neither DONE=ok nor SAFE_APPLY=ok.
no_success() {
    local label="$1" out="$2" rc="$3"
    if [ "$rc" -eq 0 ]; then bad "$label: exits non-zero" "rc=0
$out"; else ok "$label: exits non-zero"; fi
    if printf '%s\n' "$out" | grep -qE '^(DONE=ok|SAFE_APPLY=ok)'; then
        bad "$label: prints no success line" "$out"
    else
        ok "$label: prints no success line"
    fi
}

# --- 1. plain regular hyprland.lua in the target, through safe-apply.sh -------
d="$tmp/t1"; mkdir -p "$d"
printf -- '-- autogenerated by Hyprland 0.56\nhl.config({ autogenerated = true })\n' > "$d/hyprland.lua"
out="$(HYPR_DIR="$d" bash "$RS/safe-apply.sh" "$stage" 2>&1)"; rc=$?
echo "--- safe-apply into a lua-shadowed target (rc=$rc)"; printf '%s\n' "$out" | sed 's/^/    /'
no_success "AC-1 via safe-apply.sh" "$out" "$rc"
if [ -e "$d/hyprland.conf" ]; then bad "AC-1 via safe-apply.sh: nothing was installed" "hyprland.conf appeared"; else ok "AC-1 via safe-apply.sh: nothing was installed"; fi
echo

# --- 2. hyprland.lua reached through a SYMLINK (the dotfiles shape) ----------
d="$tmp/t2"; mkdir -p "$d" "$tmp/dots"
printf -- 'hl.config({})\n' > "$tmp/dots/hyprland.lua"
ln -s "$tmp/dots/hyprland.lua" "$d/hyprland.lua"
out="$(HYPR_DIR="$d" bash "$RS/install-config.sh" "$stage" 2>&1)"; rc=$?
echo "--- install into a target whose hyprland.lua is a symlink (rc=$rc)"; printf '%s\n' "$out" | sed 's/^/    /'
no_success "AC-1 with a symlinked hyprland.lua" "$out" "$rc"
echo

# --- 3. hyprland.lua reached through a DANGLING symlink ---------------------
# stow/chezmoi leave these when the dotfiles tree is not checked out yet.
# Hyprland's own lookup is a stat of the path; a .conf installed beside it is a
# write whose fate the plugin cannot vouch for.
d="$tmp/t3"; mkdir -p "$d"
ln -s "$tmp/nowhere/hyprland.lua" "$d/hyprland.lua"
out="$(HYPR_DIR="$d" bash "$RS/install-config.sh" "$stage" 2>&1)"; rc=$?
echo "--- install into a target whose hyprland.lua is a DANGLING symlink (rc=$rc)"; printf '%s\n' "$out" | sed 's/^/    /'
if [ "$rc" -eq 0 ]; then
    echo "NOTE  a dangling hyprland.lua symlink does NOT trip the shadow guard (informational)"
else
    ok "AC-1 with a dangling hyprland.lua symlink: refused"
fi
echo

# --- 4. reset-config.sh with an undetectable version -------------------------
d="$tmp/t4"; mkdir -p "$d"
printf 'old config\n' > "$d/hyprland.conf"
before="$(cat "$d/hyprland.conf")"
out="$(HYPR_DIR="$d" HYPR_VERSION=unknown PATH=/usr/bin:/bin bash "$RS/reset-config.sh" 2>&1)"; rc=$?
echo "--- reset-config.sh on an undetectable version (rc=$rc)"; printf '%s\n' "$out" | sed 's/^/    /'
if [ "$rc" -ne 0 ]; then ok "AC-5 via reset-config.sh: refuses"; else bad "AC-5 via reset-config.sh: refuses" "rc=0"; fi
if [ "$before" = "$(cat "$d/hyprland.conf")" ]; then
    ok "AC-5 via reset-config.sh: the existing config is untouched"
else
    bad "AC-5 via reset-config.sh: the existing config is untouched" "it changed"
fi
shopt -s nullglob
baks=("$tmp"/t4.bak.*)
shopt -u nullglob
if [ "${#baks[@]}" -eq 0 ]; then ok "AC-5 via reset-config.sh: took no backup for a run it refused"; else bad "AC-5 via reset-config.sh: took no backup for a run it refused" "${baks[*]}"; fi
echo

# --- 5. reset-config.sh on a lua-language version, target already has lua ----
d="$tmp/t5"; mkdir -p "$d"
printf -- '-- user lua\n' > "$d/hyprland.lua"
out="$(HYPR_DIR="$d" HYPR_VERSION=0.56.2 PATH=/usr/bin:/bin bash "$RS/reset-config.sh" 2>&1)"; rc=$?
echo "--- reset-config.sh on 0.56.2 (rc=$rc)"; printf '%s\n' "$out" | sed 's/^/    /'
if [ -f "$d/hyprland.lua" ] && ! [ -f "$d/hyprland.conf" ]; then
    ok "AC-2 via reset-config.sh: the bare config it wrote is lua, not .conf"
else
    bad "AC-2 via reset-config.sh: the bare config it wrote is lua, not .conf" "$(ls -A "$d")"
fi
if grep -q 'CONFIG_LANGUAGE_RANGE=' "$d/hyprland.lua" 2>/dev/null; then
    ok "AC-3 via reset-config.sh: the written file carries its provenance"
else
    bad "AC-3 via reset-config.sh: the written file carries its provenance" "$(head -5 "$d/hyprland.lua" 2>/dev/null)"
fi
echo

rm -rf "$tmp"
if [ "$fails" -gt 0 ]; then
    echo "REGRESS_0018_F2=fail ($fails assertion(s) failed)"
    exit 1
fi
echo "REGRESS_0018_F2=pass"
exit 0
