#!/usr/bin/env bash
# Every `${CLAUDE_PLUGIN_ROOT}/...` path mentioned in a SKILL.md / agent / command / reference
# file must exist on disk. Catches stale paths after renames/moves — exactly the bug the
# desktop-shell→rice consolidation could have introduced.
#
# Best-effort: regex-extracts paths from text. Skips paths inside code-block fences only by
# convention (most refs appear in prose). False positives (e.g. a path in an example that
# intentionally points at a generated location) are listed by name so they can be ignored
# explicitly.

# Files to scan.
mapfile -t docs < <(
    find "$PLUGIN_ROOT" -type f \
        \( -name 'SKILL.md' -o -name '*.md' \) \
        -not -path '*/.git/*' \
        -not -path '*/tests/*' \
        -not -path '*/examples/*' \
        -not -path '*/.claude/worktrees/*' \
        -not -path '*/.research/*' \
    | sort
)

# Paths the user is expected to create at runtime — exclude these from existence checks.
# Patterns are matched as plain substrings against the candidate path.
RUNTIME_PATHS=(
    "~/.config/hypr-rice/"      # generated by rice-init.sh at runtime
    "~/.config/hypr/"           # user's hypr config dir (may or may not exist)
    "~/.config/uwsm/"           # uwsm session env (when present)
    "/etc/"                     # root-side files
    "/usr/share/"               # root-side files
    "/boot/grub/"               # root-side files
    "/sys/class/"               # kernel sysfs
    "/proc/acpi/"               # kernel procfs
    "/tmp/hypr-"                # staging dirs created at runtime
)

is_runtime_path() {
    local p="$1"
    for r in "${RUNTIME_PATHS[@]}"; do
        case "$p" in *"$r"*) return 0 ;; esac
    done
    return 1
}

total=0
missing=()
for d in "${docs[@]}"; do
    # Pull every `${CLAUDE_PLUGIN_ROOT}/...` reference. The path ends at the first space,
    # backtick, quote, paren, or semicolon.
    while IFS= read -r ref; do
        # Strip the prefix.
        rel="${ref#\$\{CLAUDE_PLUGIN_ROOT\}/}"
        rel="${rel#CLAUDE_PLUGIN_ROOT/}"
        # Drop trailing punctuation that grep picks up.
        rel="${rel%[.,)\`\"\']}"
        rel="${rel%/}"
        total=$((total + 1))
        if [ ! -e "$PLUGIN_ROOT/$rel" ]; then
            missing+=("$d → $rel")
        fi
    done < <(grep -oE '\$\{CLAUDE_PLUGIN_ROOT\}/[A-Za-z0-9_./\-]+' "$d" 2>/dev/null)
done

if [ "${#missing[@]}" -eq 0 ]; then
    pass "every \${CLAUDE_PLUGIN_ROOT}/ ref resolves ($total checked)"
else
    detail=""
    for m in "${missing[@]}"; do detail+="$m"$'\n'; done
    fail "${#missing[@]} stale \${CLAUDE_PLUGIN_ROOT}/ refs (of $total)" "$detail"
fi

# Also check unambiguous relative-path refs — only `./...` or `../...`, not bare filenames in
# backticks (those are just mentions in prose, not paths to resolve).
rel_missing=()
rel_total=0
for d in "${docs[@]}"; do
    base="$(dirname "$d")"
    # Match `./path` or `../path` inside backticks. Path can contain word chars, /, ., -.
    while IFS= read -r raw; do
        p="${raw//\`/}"
        rel_total=$((rel_total + 1))
        candidate="$base/$p"
        if command -v realpath >/dev/null 2>&1; then
            resolved="$(realpath -m "$candidate")"
        else
            resolved="$candidate"
        fi
        if [ ! -e "$resolved" ]; then
            rel_missing+=("$d → $p")
        fi
    done < <(grep -oE '`\.\.?/[A-Za-z0-9_./\-]+`' "$d" 2>/dev/null)
done

if [ "${#rel_missing[@]}" -eq 0 ]; then
    pass "relative-path refs (./ or ../) resolve ($rel_total checked)"
else
    detail=""
    for m in "${rel_missing[@]}"; do detail+="$m"$'\n'; done
    fail "${#rel_missing[@]} stale relative refs (of $rel_total)" "$detail"
fi
