#!/usr/bin/env bash
# S0018-hyprland-config-lua-4 - impl-gate loop 1 regression artifact F2 (advisory).
#
# Written by the refuter; kept verbatim in substance and moved into the suite
# (`regress_0018_F2.sh` -> `test_regress_0018_F2.sh`) so `tests/run.sh` discovers
# it. The assertions are the refuter's; only the reporting was rewired onto
# tests/lib.sh, and the dangling-symlink case - which the refuter could only
# record as informational because the guard let it through - is now a real
# assertion, because the guard was fixed.
#
# AC-1: "IF the Hyprland config directory already contains a hyprland.lua THEN
#        THE SYSTEM SHALL NOT install a hyprlang .conf and SHALL report that the
#        lua config takes precedence over it"
#
# The spec's Objective names the exact failure to close: "a SAFE_APPLY=ok printed
# for a change that the compositor never read". So this probe drives the WHOLE
# apply path (safe-apply.sh -> install-config.sh) and every shadow shape it can
# reach, asserting that none of them ends in an ok/DONE line.

RS="$PLUGIN_ROOT/skills/rice/scripts"

tmp="$(mktemp_test_dir regress0018F2)"
stage="$tmp/stage-conf"
HYPR_CONFIG_LANG=hyprlang HYPR_VERSION=0.54.3 bash "$RS/emit-config.sh" "$stage" >/dev/null 2>&1

# `no_success <label> <output> <rc>` - a refusal must be non-zero and must carry
# neither DONE=ok nor SAFE_APPLY=ok.
no_success() {
    local label="$1" out="$2" rc="$3"
    if [ "$rc" -eq 0 ]; then
        fail "$label: exits non-zero" "rc=0
$out"
    else
        pass "$label: exits non-zero"
    fi
    if printf '%s\n' "$out" | grep -qE '^(DONE=ok|SAFE_APPLY=ok)'; then
        fail "$label: prints no success line" "$out"
    else
        pass "$label: prints no success line"
    fi
}

# --- 1. plain regular hyprland.lua in the target, through safe-apply.sh -------
d="$tmp/t1"; mkdir -p "$d"
printf -- '-- autogenerated by Hyprland 0.56\nhl.config({ autogenerated = true })\n' > "$d/hyprland.lua"
out="$(HYPR_DIR="$d" bash "$RS/safe-apply.sh" "$stage" 2>&1)"; rc=$?
no_success "F2/AC-1 via safe-apply.sh" "$out" "$rc"
if [ -e "$d/hyprland.conf" ]; then
    fail "F2/AC-1 via safe-apply.sh: nothing was installed" "hyprland.conf appeared"
else
    pass "F2/AC-1 via safe-apply.sh: nothing was installed"
fi

# --- 2. hyprland.lua reached through a SYMLINK (the dotfiles shape) ----------
d="$tmp/t2"; mkdir -p "$d" "$tmp/dots"
printf -- 'hl.config({})\n' > "$tmp/dots/hyprland.lua"
ln -s "$tmp/dots/hyprland.lua" "$d/hyprland.lua"
out="$(HYPR_DIR="$d" bash "$RS/install-config.sh" "$stage" 2>&1)"; rc=$?
no_success "F2/AC-1 with a symlinked hyprland.lua" "$out" "$rc"

# --- 3. hyprland.lua reached through a DANGLING symlink ---------------------
# stow/chezmoi leave these when the dotfiles tree is not checked out yet.
# Hyprland's own lookup is a stat of the path; a .conf installed beside it is a
# write whose fate the plugin cannot vouch for, so the guard refuses it too.
d="$tmp/t3"; mkdir -p "$d"
ln -s "$tmp/nowhere/hyprland.lua" "$d/hyprland.lua"
out="$(HYPR_DIR="$d" bash "$RS/install-config.sh" "$stage" 2>&1)"; rc=$?
no_success "F2/AC-1 with a DANGLING hyprland.lua symlink" "$out" "$rc"
if [ -e "$d/hyprland.conf" ]; then
    fail "F2/AC-1 with a dangling symlink: nothing was installed" "hyprland.conf appeared"
else
    pass "F2/AC-1 with a dangling symlink: nothing was installed"
fi

# --- 4. reset-config.sh with an undetectable version -------------------------
d="$tmp/t4"; mkdir -p "$d"
printf 'old config\n' > "$d/hyprland.conf"
before="$(cat "$d/hyprland.conf")"
out="$(HYPR_DIR="$d" HYPR_VERSION=unknown PATH=/usr/bin:/bin bash "$RS/reset-config.sh" 2>&1)"; rc=$?
if [ "$rc" -ne 0 ]; then
    pass "F2/AC-5 via reset-config.sh: refuses"
else
    fail "F2/AC-5 via reset-config.sh: refuses" "rc=0
$out"
fi
assert_eq "$before" "$(cat "$d/hyprland.conf")" \
    "F2/AC-5 via reset-config.sh: the existing config is untouched"
shopt -s nullglob
baks=("$tmp"/t4.bak.*)
shopt -u nullglob
if [ "${#baks[@]}" -eq 0 ]; then
    pass "F2/AC-5 via reset-config.sh: took no backup for a run it refused"
else
    fail "F2/AC-5 via reset-config.sh: took no backup for a run it refused" "${baks[*]}"
fi

# --- 5. reset-config.sh on a lua-language version, target already has lua ----
d="$tmp/t5"; mkdir -p "$d"
printf -- '-- user lua\n' > "$d/hyprland.lua"
out="$(HYPR_DIR="$d" HYPR_VERSION=0.56.2 PATH=/usr/bin:/bin bash "$RS/reset-config.sh" 2>&1)"; rc=$?
if [ -f "$d/hyprland.lua" ] && ! [ -f "$d/hyprland.conf" ]; then
    pass "F2/AC-2 via reset-config.sh: the bare config it wrote is lua, not .conf"
else
    fail "F2/AC-2 via reset-config.sh: the bare config it wrote is lua, not .conf" "$(ls -A "$d")"
fi
if grep -q 'CONFIG_LANGUAGE_RANGE=' "$d/hyprland.lua" 2>/dev/null; then
    pass "F2/AC-3 via reset-config.sh: the written file carries its provenance"
else
    fail "F2/AC-3 via reset-config.sh: the written file carries its provenance" \
        "$(head -5 "$d/hyprland.lua" 2>/dev/null)"
fi

rm -rf "$tmp"
