#!/usr/bin/env bash
# LUA-4 / S0018 - converting a .conf this plugin already wrote into lua.
#
# Grades:
#   AC-4  the conversion is OFFERED, and a converted config keeps the .conf as a
#         backup rather than deleting it
#   AC-9  a config that does not parse as the language it claims to be is refused
#         by name, leaving the original file and the install target unchanged
#   AC-10 a backup step that does not produce a readable copy aborts BEFORE any lua
#         is written, and says it aborted because the backup failed
#   AC-11 a conversion against a directory that already holds a hyprland.lua refuses
#         rather than overwriting it, naming the file it declined to replace
#
# Everything runs against a temporary HYPR_DIR; no real ~/.config/hypr is touched.

RS="$PLUGIN_ROOT/skills/rice/scripts"
migrate="$RS/migrate-config.sh"
emit="$RS/emit-config.sh"

assert_file_exists "$migrate" "migrate-config.sh ships"

tmp="$(mktemp_test_dir hypr-lua-migrate)"

# `seed_conf <dir>` - a .conf configuration of the kind an earlier release of this
# plugin wrote: generated by the plugin's own hyprlang emitter.
seed_conf() {
    local d="$1"
    rm -rf "$d"
    mkdir -p "$d"
    HYPR_CONFIG_LANG=hyprlang HYPR_VERSION=0.54.3 bash "$emit" "$d" >/dev/null 2>&1
}

# --------------------------------------------------------------------------------------------
# AC-4 (offer) - the default run reports what it WOULD do and changes nothing
# --------------------------------------------------------------------------------------------
dir="$tmp/offer"
seed_conf "$dir"
assert_file_exists "$dir/hyprland.conf" "AC-4: seeded a plugin-written .conf"
conf_before="$(cat "$dir/hyprland.conf")"

out="$(HYPR_DIR="$dir" bash "$migrate" 2>&1)"; rc=$?
assert_eq "0" "$rc" "AC-4: the offer itself succeeds"
if printf '%s\n' "$out" | grep -q '^MIGRATE_OFFER='; then
    pass "AC-4: it offers to convert the .conf to lua"
else
    fail "AC-4: it offers to convert the .conf to lua" "$out"
fi
if printf '%s\n' "$out" | grep -q "^WOULD_WRITE=$dir/hyprland.lua"; then
    pass "AC-4: the offer names the lua file it would write"
else
    fail "AC-4: the offer names the lua file it would write" "$out"
fi
if printf '%s\n' "$out" | grep -q "^WOULD_KEEP=$dir/hyprland.conf"; then
    pass "AC-4: the offer says the .conf would be kept"
else
    fail "AC-4: the offer says the .conf would be kept" "$out"
fi
if printf '%s\n' "$out" | grep -q '^ACCEPT_WITH='; then
    pass "AC-4: the offer says how to accept it"
else
    fail "AC-4: the offer says how to accept it" "$out"
fi
if [ -e "$dir/hyprland.lua" ]; then
    fail "AC-4: the offer alone writes no lua" "found $dir/hyprland.lua"
else
    pass "AC-4: the offer alone writes no lua"
fi
assert_eq "$conf_before" "$(cat "$dir/hyprland.conf")" "AC-4: the offer alone changes no .conf"

# --------------------------------------------------------------------------------------------
# AC-4 (convert) - accepting it writes lua and KEEPS the .conf as a backup
# --------------------------------------------------------------------------------------------
dir="$tmp/convert"
seed_conf "$dir"
conf_before="$(cat "$dir/hyprland.conf")"

out="$(HYPR_DIR="$dir" bash "$migrate" --convert 2>&1)"; rc=$?
assert_eq "0" "$rc" "AC-4: the conversion succeeds"
if printf '%s\n' "$out" | grep -q '^MIGRATE=ok'; then
    pass "AC-4: the conversion reports MIGRATE=ok"
else
    fail "AC-4: the conversion reports MIGRATE=ok" "$out"
fi
assert_file_exists "$dir/hyprland.lua" "AC-4: a lua configuration is produced"
assert_file_exists "$dir/hyprland.conf" "AC-4: the .conf is NOT deleted"
assert_eq "$conf_before" "$(cat "$dir/hyprland.conf")" "AC-4: the kept .conf is byte-identical"

backed_up="$(printf '%s\n' "$out" | sed -n 's/^BACKED_UP=//p' | head -n1)"
if [ -n "$backed_up" ] && [ -r "$backed_up" ]; then
    pass "AC-4: a readable backup copy of the .conf was made"
else
    fail "AC-4: a readable backup copy of the .conf was made" "BACKED_UP=$backed_up"
fi
if [ -n "$backed_up" ] && cmp -s "$dir/hyprland.conf" "$backed_up"; then
    pass "AC-4: the backup is a faithful copy of the original .conf"
else
    fail "AC-4: the backup is a faithful copy of the original .conf" "BACKED_UP=$backed_up"
fi

# The produced lua is lua, and it says what it is (AC-3's rule applies to it too).
assert_file_contains "$dir/hyprland.lua" "hl.config({" "AC-4: the produced lua uses the lua config API"
assert_grep '^-- CONFIG_LANGUAGE=lua$' "$dir/hyprland.lua" \
    "AC-4: the produced lua records the language it is"
assert_grep '^-- CONFIG_LANGUAGE_RANGE=Hyprland 0\.55 and newer' "$dir/hyprland.lua" \
    "AC-4: the produced lua records the range it is valid for"
assert_grep '^hl\.bind\("SUPER \+ Return", hl\.dsp\.exec_cmd\("kitty"\)\)$' "$dir/hyprland.lua" \
    "AC-4: a hyprlang bind became the lua bind, with the \$variable expanded"
assert_grep '^hl\.monitor\(\{ output = "", mode = "preferred"' "$dir/hyprland.lua" \
    "AC-4: the monitor line became hl.monitor"

# A second conversion now hits the existing-lua refusal, which is AC-11's rule.
out="$(HYPR_DIR="$dir" bash "$migrate" --convert 2>&1)"; rc=$?
assert_eq "4" "$rc" "AC-4: re-running the conversion does not silently redo it"

# Sourced .conf modules travel with the main file.
dir="$tmp/modular"
seed_conf "$dir"
printf '# extra module\nenv = XCURSOR_SIZE,24\nexec-once = waybar\n' > "$dir/extra.conf"
printf 'source = ~/nope\n' > /dev/null   # (documentation of the form; not used)
printf '\nsource = %s/extra.conf\n' "$dir" >> "$dir/hyprland.conf"
out="$(HYPR_DIR="$dir" bash "$migrate" --convert 2>&1)"; rc=$?
assert_eq "0" "$rc" "AC-4: a modular .conf set converts as one unit"
assert_file_exists "$dir/extra.lua" "AC-4: the sourced module is converted too"
assert_file_exists "$dir/extra.conf" "AC-4: the sourced module's .conf is kept too"
assert_file_contains "$dir/hyprland.lua" 'require("extra")' \
    "AC-4: the main lua requires the converted module"
assert_file_contains "$dir/extra.lua" 'hl.env("XCURSOR_SIZE", "24")' \
    "AC-4: env lines became hl.env"
assert_file_contains "$dir/extra.lua" 'hl.exec_cmd("waybar")' \
    "AC-4: exec-once lines became hl.exec_cmd"

# --------------------------------------------------------------------------------------------
# AC-4, the shape the plugin ACTUALLY installs: the modular `source = ~/.config/hypr/*.conf`
# set the rice interview generates. `skills/rice/examples/sample-config/` is this repo's own
# canonical instance of "a .conf written by an earlier release of this plugin", so it is the
# population AC-4 names. Impl-gate loop 1 finding F1: the converter refused it outright.
# Impl-gate loop 1 finding F3: the `~` form was resolved against $HOME while the config set was
# resolved against $HYPR_DIR, which is why no test here had ever exercised the real shape.
# --------------------------------------------------------------------------------------------
sample="$PLUGIN_ROOT/skills/rice/examples/sample-config"
dir="$tmp/plugin-generated"
mkdir -p "$dir"
cp -a "$sample"/. "$dir"/
assert_file_contains "$dir/hyprland.conf" 'source = ~/.config/hypr/env.conf' \
    "AC-4: the sample set really does use the ~ source form"

# F3: HYPR_DIR is a scratch dir and HOME is left alone, exactly as every other test here
# drives these scripts. The ~ form must still resolve against the dir being converted.
out="$(HYPR_DIR="$dir" bash "$migrate" 2>&1)"; rc=$?
assert_eq "0" "$rc" "AC-4: the plugin's own generated config set is offered a conversion"
if printf '%s\n' "$out" | grep -q '^MIGRATE_OFFER=convert 9 '; then
    pass "AC-4: the offer covers all 9 files of the source= closure"
else
    fail "AC-4: the offer covers all 9 files of the source= closure" "$out"
fi
if printf '%s\n' "$out" | grep -q '^UNRESOLVED_SOURCE='; then
    fail "F3: a HYPR_DIR override does not make the ~ source form unresolvable" "$out"
else
    pass "F3: a HYPR_DIR override does not make the ~ source form unresolvable"
fi
if [ -e "$dir/hyprland.lua" ]; then
    fail "AC-4: the offer on the plugin's own set writes nothing"
else
    pass "AC-4: the offer on the plugin's own set writes nothing"
fi

conf_before="$(cat "$dir/hyprland.conf")"
out="$(HYPR_DIR="$dir" bash "$migrate" --convert 2>&1)"; rc=$?
assert_eq "0" "$rc" "AC-4: the plugin's own generated config set converts"
if printf '%s\n' "$out" | grep -q '^MIGRATE=ok-with-unmapped'; then
    pass "AC-4: the run reports the conversion and what did not map"
else
    fail "AC-4: the run reports the conversion and what did not map" "$out"
fi
assert_file_exists "$dir/hyprland.lua" "AC-4: a lua config is produced for the plugin's own set"
for m in env colors monitors input looknfeel binds windowrules autostart; do
    assert_file_exists "$dir/$m.lua" "AC-4: sourced module $m.conf was converted too"
    assert_file_exists "$dir/$m.conf" "AC-4: sourced module $m.conf was kept"
    assert_file_contains "$dir/hyprland.lua" "require(\"$m\")" \
        "AC-4: the main lua requires the converted $m module"
done
assert_eq "$conf_before" "$(cat "$dir/hyprland.conf")" "AC-4: the main .conf is byte-identical"
for b in "$dir"/*.conf.pre-lua.*; do
    orig="${b%%.pre-lua.*}"
    if [ -r "$b" ] && cmp -s "$orig" "$b"; then
        pass "AC-4: $(basename "$orig") has a readable, faithful backup"
    else
        fail "AC-4: $(basename "$orig") has a readable, faithful backup" "$b"
    fi
done

# The documented lua vocabulary the plugin's own output needs.
assert_grep '^\s+\["col\.active_border"\] = "rgb\(cba6f7\) rgb\(89b4fa\) 45deg",$' "$dir/looknfeel.lua" \
    "AC-4: a hyprlang key that is not a lua identifier becomes a lua bracket key, \$vars expanded"
assert_grep '^\s+\["tap-to-click"\] = true,$' "$dir/input.lua" \
    "AC-4: a hyphenated hyprlang key becomes a lua bracket key too"
assert_file_contains "$dir/windowrules.lua" 'hl.window_rule({' \
    "AC-4: a windowrule block became hl.window_rule"
assert_file_contains "$dir/windowrules.lua" 'hl.layer_rule({' \
    "AC-4: a layerrule block became hl.layer_rule"
assert_grep '^\s+class = "\^\(pavucontrol\|nm-connection-editor\|blueman-manager\)\$",$' \
    "$dir/windowrules.lua" "AC-4: match:class selectors became a match = { ... } sub-table"
assert_file_contains "$dir/monitors.lua" 'hl.monitor({ output = ""' \
    "AC-4: the monitor line became hl.monitor"

# ... and what it cannot map is carried across, marked, counted and reported - never dropped.
if printf '%s\n' "$out" | grep -q '^NOT_APPLIED_COUNT=18$'; then
    pass "AC-4: all 18 unmappable lines (5 bezier, 12 animation, 1 gesture) are reported"
else
    fail "AC-4: all 18 unmappable lines (5 bezier, 12 animation, 1 gesture) are reported" \
        "$(printf '%s\n' "$out" | grep '^NOT_APPLIED_COUNT=' || echo '<none>')"
fi
assert_grep "^ +-- NOT APPLIED \('animation' is a repeatable" "$dir/looknfeel.lua" \
    "AC-4: the animation lines are in the lua as marked comments, not dropped"
assert_grep "^-- NOT APPLIED \('gesture' has no documented" "$dir/input.lua" \
    "AC-4: the gesture line is in the lua as a marked comment, not dropped"
if grep -qE '^\s*(bezier|animation|gesture) = ' "$dir/looknfeel.lua" "$dir/input.lua"; then
    fail "AC-4: no unmapped hyprlang keyword leaked into the lua as a table key"
else
    pass "AC-4: no unmapped hyprlang keyword leaked into the lua as a table key"
fi
if printf '%s\n' "$out" | grep -q '^UNPARSEABLE='; then
    fail "F1: the plugin's own generated config is never called unparseable" "$out"
else
    pass "F1: the plugin's own generated config is never called unparseable"
fi

# --------------------------------------------------------------------------------------------
# AC-9 - a .conf that does not parse as hyprlang is refused by name
# --------------------------------------------------------------------------------------------
dir="$tmp/unparseable"
seed_conf "$dir"
cat >> "$dir/hyprland.conf" <<'BROKEN'
this line is not hyprlang at all
}
BROKEN
conf_before="$(cat "$dir/hyprland.conf")"
before_listing="$(cd "$dir" && ls -A | sort | tr '\n' ' ')"

out="$(HYPR_DIR="$dir" bash "$migrate" --convert 2>&1)"; rc=$?
assert_eq "3" "$rc" "AC-9: an unparseable config is refused"
if printf '%s\n' "$out" | grep -q '^MIGRATE=refused-unparseable'; then
    pass "AC-9: the refusal is reported as unparseable"
else
    fail "AC-9: the refusal is reported as unparseable" "$out"
fi
if printf '%s\n' "$out" | grep -q 'UNPARSEABLE=.*hyprland.conf:.*this line is not hyprlang at all'; then
    pass "AC-9: the refusal names the line it could not parse"
else
    fail "AC-9: the refusal names the line it could not parse" "$out"
fi
if printf '%s\n' "$out" | grep -q "UNPARSEABLE=.*stray '}'"; then
    pass "AC-9: the refusal names the stray brace too"
else
    fail "AC-9: the refusal names the stray brace too" "$out"
fi
assert_eq "$conf_before" "$(cat "$dir/hyprland.conf")" "AC-9: the original .conf is unchanged"
assert_eq "$before_listing" "$(cd "$dir" && ls -A | sort | tr '\n' ' ')" \
    "AC-9: the install target is unchanged - no lua, no backup, nothing added"

# The offer mode of an unparseable config refuses identically - it never claims a
# conversion it cannot perform.
out="$(HYPR_DIR="$dir" bash "$migrate" 2>&1)"; rc=$?
assert_eq "3" "$rc" "AC-9: the OFFER for an unparseable config refuses too"
if printf '%s\n' "$out" | grep -q '^MIGRATE_OFFER='; then
    fail "AC-9: no offer is made for a config that does not parse" "$out"
else
    pass "AC-9: no offer is made for a config that does not parse"
fi

# AC-9's boundary. A construct that PARSES but has no documented lua mapping is a
# different thing, and must not be reported as unparseable: that is what made the
# plugin's own generated config unconvertible at impl-gate loop 1 (finding F1).
# It is carried across as a marked comment and reported line by line instead.
dir="$tmp/unmappable"
seed_conf "$dir"
printf '\nbezier = wind, 0.05, 0.9, 0.1, 1.05\n' >> "$dir/hyprland.conf"
conf_before="$(cat "$dir/hyprland.conf")"
out="$(HYPR_DIR="$dir" bash "$migrate" --convert 2>&1)"; rc=$?
assert_eq "0" "$rc" "AC-9 boundary: a parseable-but-unmappable construct is NOT refused"
if printf '%s\n' "$out" | grep -q '^MIGRATE=ok-with-unmapped'; then
    pass "AC-9 boundary: the run says plainly that something did not map"
else
    fail "AC-9 boundary: the run says plainly that something did not map" "$out"
fi
if printf '%s\n' "$out" | grep -q '^MIGRATE=refused-unparseable'; then
    fail "AC-9 boundary: an unmappable construct is not called unparseable" "$out"
else
    pass "AC-9 boundary: an unmappable construct is not called unparseable"
fi
if printf '%s\n' "$out" | grep -q "^NOT_APPLIED=.*hyprland\.conf:.*'bezier' has no documented lua mapping"; then
    pass "AC-9 boundary: the run names the construct it could not map, by file and line"
else
    fail "AC-9 boundary: the run names the construct it could not map, by file and line" "$out"
fi
assert_grep '^-- NOT APPLIED \(.*bezier = wind, 0\.05' "$dir/hyprland.lua" \
    "AC-9 boundary: the unmapped line is carried into the lua verbatim, marked NOT APPLIED"
assert_grep '^-- NOT APPLIED: 1 line' "$dir/hyprland.lua" \
    "AC-9 boundary: the produced file's header counts what does not apply"
assert_eq "$conf_before" "$(cat "$dir/hyprland.conf")" \
    "AC-9 boundary: the .conf still holds the line, so it can be ported by hand"

# The offer says so BEFORE anything is accepted.
dir="$tmp/unmappable-offer"
seed_conf "$dir"
printf '\nbezier = wind, 0.05, 0.9, 0.1, 1.05\n' >> "$dir/hyprland.conf"
before_listing="$(cd "$dir" && ls -A | sort | tr '\n' ' ')"
out="$(HYPR_DIR="$dir" bash "$migrate" 2>&1)"; rc=$?
assert_eq "0" "$rc" "AC-4: the offer for a partly-unmappable config still succeeds"
if printf '%s\n' "$out" | grep -q "^WOULD_NOT_APPLY=.*'bezier'"; then
    pass "AC-4: the offer warns which lines would stop applying, before you accept"
else
    fail "AC-4: the offer warns which lines would stop applying, before you accept" "$out"
fi
assert_eq "$before_listing" "$(cd "$dir" && ls -A | sort | tr '\n' ' ')" \
    "AC-4: that offer still changed nothing"

# --------------------------------------------------------------------------------------------
# A `source =` the converter cannot resolve is a refusal, not a carry-over: it cannot
# report what a conversion would cost for a file it has never read.
# --------------------------------------------------------------------------------------------
dir="$tmp/bad-source"
seed_conf "$dir"
printf '\nsource = %s/missing.conf\n' "$dir" >> "$dir/hyprland.conf"
before_listing="$(cd "$dir" && ls -A | sort | tr '\n' ' ')"
out="$(HYPR_DIR="$dir" bash "$migrate" --convert 2>&1)"; rc=$?
assert_eq "3" "$rc" "a source= that cannot be resolved is refused"
if printf '%s\n' "$out" | grep -q '^MIGRATE=refused-unresolvable-source'; then
    pass "the unresolvable source is reported as its own refusal, not as unparseable"
else
    fail "the unresolvable source is reported as its own refusal, not as unparseable" "$out"
fi
if printf '%s\n' "$out" | grep -q '^UNRESOLVED_SOURCE=.*missing.conf'; then
    pass "the refusal names the source it could not resolve"
else
    fail "the refusal names the source it could not resolve" "$out"
fi
assert_eq "$before_listing" "$(cd "$dir" && ls -A | sort | tr '\n' ' ')" \
    "nothing was written for the unresolvable source"

# --------------------------------------------------------------------------------------------
# AC-10 - a failed backup aborts BEFORE any lua is written
# --------------------------------------------------------------------------------------------
dir="$tmp/backup-fails"
seed_conf "$dir"
conf_before="$(cat "$dir/hyprland.conf")"
before_listing="$(cd "$dir" && ls -A | sort | tr '\n' ' ')"
# A backup destination that cannot exist: its parent is a regular file, so no
# uid - root included - can create a directory there.
blocker="$tmp/blocker-file"
printf 'not a directory\n' > "$blocker"

out="$(HYPR_DIR="$dir" HYPR_BACKUP_DIR="$blocker/backups" bash "$migrate" --convert 2>&1)"; rc=$?
assert_eq "5" "$rc" "AC-10: a failed backup aborts with a distinct non-zero status"
if printf '%s\n' "$out" | grep -q '^MIGRATE=aborted-backup-failed'; then
    pass "AC-10: it reports that it aborted because the backup failed"
else
    fail "AC-10: it reports that it aborted because the backup failed" "$out"
fi
if printf '%s\n' "$out" | grep -q '^BACKUP_FAILED='; then
    pass "AC-10: it names the backup destination that failed"
else
    fail "AC-10: it names the backup destination that failed" "$out"
fi
if [ -e "$dir/hyprland.lua" ]; then
    fail "AC-10: it wrote no lua before aborting" "found $dir/hyprland.lua"
else
    pass "AC-10: it wrote no lua before aborting"
fi
assert_eq "$conf_before" "$(cat "$dir/hyprland.conf")" "AC-10: the original .conf is unchanged"
assert_eq "$before_listing" "$(cd "$dir" && ls -A | sort | tr '\n' ' ')" \
    "AC-10: the config dir is exactly as it was"

# Same story when the backup directory exists but cannot be written into.
if [ "$(id -u)" = "0" ]; then
    skip "AC-10: unwritable backup dir" "running as root; permission bits are not enforced"
else
    dir="$tmp/backup-unwritable"
    seed_conf "$dir"
    ro="$tmp/readonly-backups"
    mkdir -p "$ro"
    chmod 500 "$ro"
    before_listing="$(cd "$dir" && ls -A | sort | tr '\n' ' ')"
    out="$(HYPR_DIR="$dir" HYPR_BACKUP_DIR="$ro" bash "$migrate" --convert 2>&1)"; rc=$?
    chmod 700 "$ro"
    assert_eq "5" "$rc" "AC-10: an unwritable backup dir aborts too"
    if printf '%s\n' "$out" | grep -q '^MIGRATE=aborted-backup-failed'; then
        pass "AC-10: the unwritable backup dir is reported as a backup failure"
    else
        fail "AC-10: the unwritable backup dir is reported as a backup failure" "$out"
    fi
    if [ -e "$dir/hyprland.lua" ]; then
        fail "AC-10: no lua was written when the backup dir was unwritable" "found $dir/hyprland.lua"
    else
        pass "AC-10: no lua was written when the backup dir was unwritable"
    fi
    assert_eq "$before_listing" "$(cd "$dir" && ls -A | sort | tr '\n' ' ')" \
        "AC-10: the config dir is exactly as it was"
fi

# --------------------------------------------------------------------------------------------
# AC-11 - an existing hyprland.lua is never overwritten
# --------------------------------------------------------------------------------------------
dir="$tmp/already-lua"
seed_conf "$dir"
printf -- '-- hand written, do not clobber\nhl.config({ general = { gaps_in = 7 } })\n' > "$dir/hyprland.lua"
lua_before="$(cat "$dir/hyprland.lua")"
conf_before="$(cat "$dir/hyprland.conf")"

for args in "" "--convert"; do
    label="${args:-offer}"
    # shellcheck disable=SC2086
    out="$(HYPR_DIR="$dir" bash "$migrate" $args 2>&1)"; rc=$?
    assert_eq "4" "$rc" "AC-11: a conversion ($label) against a dir with a hyprland.lua refuses"
    if printf '%s\n' "$out" | grep -q '^MIGRATE=refused-existing-lua'; then
        pass "AC-11: the refusal ($label) is reported as an existing lua config"
    else
        fail "AC-11: the refusal ($label) is reported as an existing lua config" "$out"
    fi
    if printf '%s\n' "$out" | grep -q "^DECLINED_TO_REPLACE=$dir/hyprland.lua"; then
        pass "AC-11: the refusal ($label) names the file it declined to replace"
    else
        fail "AC-11: the refusal ($label) names the file it declined to replace" "$out"
    fi
done
assert_eq "$lua_before" "$(cat "$dir/hyprland.lua")" "AC-11: the existing hyprland.lua is untouched"
assert_eq "$conf_before" "$(cat "$dir/hyprland.conf")" "AC-11: the .conf is untouched too"

# The same refusal covers a sourced module whose .lua counterpart already exists.
dir="$tmp/already-module-lua"
seed_conf "$dir"
printf 'env = XCURSOR_SIZE,24\n' > "$dir/extra.conf"
printf '\nsource = %s/extra.conf\n' "$dir" >> "$dir/hyprland.conf"
printf -- '-- hand written module\n' > "$dir/extra.lua"
extra_before="$(cat "$dir/extra.lua")"
out="$(HYPR_DIR="$dir" bash "$migrate" --convert 2>&1)"; rc=$?
assert_eq "4" "$rc" "AC-11: an existing module .lua refuses the conversion too"
if printf '%s\n' "$out" | grep -q "^DECLINED_TO_REPLACE=$dir/extra.lua"; then
    pass "AC-11: the refusal names the module file it declined to replace"
else
    fail "AC-11: the refusal names the module file it declined to replace" "$out"
fi
assert_eq "$extra_before" "$(cat "$dir/extra.lua")" "AC-11: that module .lua is untouched"
if [ -e "$dir/hyprland.lua" ]; then
    fail "AC-11: no main lua was written either" "found $dir/hyprland.lua"
else
    pass "AC-11: no main lua was written either"
fi

# --------------------------------------------------------------------------------------------
# Nothing to convert is not an error.
# --------------------------------------------------------------------------------------------
dir="$tmp/empty-dir"
mkdir -p "$dir"
out="$(HYPR_DIR="$dir" bash "$migrate" 2>&1)"; rc=$?
assert_eq "0" "$rc" "a directory with no .conf is not an error"
if printf '%s\n' "$out" | grep -q '^MIGRATE=nothing-to-convert'; then
    pass "a directory with no .conf reports nothing to convert"
else
    fail "a directory with no .conf reports nothing to convert" "$out"
fi

rm -rf "$tmp"
