#!/usr/bin/env python3
"""Which config LANGUAGE this Hyprland reads - a DETECTION FACT, never a default.

Since 0.55 Hyprland reads `hyprland.lua` and loads it INSTEAD OF `hyprland.conf`, and since
0.56.0 a fresh install autogenerates one. Guessing wrong is not a cosmetic error: it is a config
the compositor never reads, while every check this plugin runs reports success against the file
it wrote.

So on an undetectable version this REFUSES and asks. `EMITTABLE_LANGUAGES=lua hyprlang` is
printed with each option's support range, and an explicit `HYPR_CONFIG_LANG` (or `--language`)
is required. Relaying that question to the user is the whole point - it is not a default anyone
can pick for them.

Usage: config-language.sh [--language <lua|hyprlang>] [--version <x.y.z>] [--range <lang>]
Exit:  0 decided, 2 bad input, 3 undecidable (the caller must ask).
"""
import os
import sys

# The release where lua became the documented config language.
CLIFF = "0.55"

RANGES = {
    "lua": (f"Hyprland {CLIFF} and newer (lua is the documented config language since {CLIFF})"),
    # Kept on one line on purpose: the published support window is grepped for verbatim by
    # tests/test_lua_emit.sh, and a phrase split across two string literals is not findable.
    "hyprlang": f"Hyprland up to 0.54; deprecated since {CLIFF} and supported for 1 - 2 releases starting from {CLIFF}, after which hyprlang is dropped",
}
FILES = {"lua": "hyprland.lua", "hyprlang": "hyprland.conf"}
COMMENTS = {"lua": "--", "hyprlang": "#"}


def lang_range(lang):
    return RANGES.get(lang)


def lang_file(lang):
    return FILES.get(lang)


def lang_comment(lang):
    return COMMENTS.get(lang)


def lang_of_file(path):
    if path.endswith(".lua"):
        return "lua"
    if path.endswith(".conf"):
        return "hyprlang"
    return None


def provenance(lang):
    """The header every emitted config carries: what wrote it, in which language, and the
    version range that language is valid for. A file that outlives the session that made it
    should still say what it is."""
    c, r = lang_comment(lang), lang_range(lang)
    if not c or not r:
        return None
    return (f"{c} Generated by the hyprland-config plugin.\n"
            f"{c} CONFIG_LANGUAGE={lang}\n"
            f"{c} CONFIG_LANGUAGE_RANGE={r}\n")


def for_version(v):
    """`lua` at 0.55+, `hyprlang` below, `unknown` when the version cannot be read as one."""
    if not v or v.lower() == "unknown":
        return "unknown"
    v = v.lstrip("v")
    parts = v.split(".")
    major = parts[0]
    minor = parts[1] if len(parts) > 1 else "0"
    if not major.isdigit() or not minor.isdigit():
        return "unknown"
    major, minor = int(major), int(minor)
    if major >= 1 or (major == 0 and minor >= 55):
        return "lua"
    return "hyprlang"


def report_undecided(out=sys.stdout):
    print("CONFIG_LANGUAGE=undecided", file=out)
    print("EMITTABLE_LANGUAGES=lua hyprlang", file=out)
    print(f"LANGUAGE_OPTION=lua {RANGES['lua']}", file=out)
    print(f"LANGUAGE_OPTION=hyprlang {RANGES['hyprlang']}", file=out)
    print("ERROR: the installed Hyprland version could not be detected, so the config language "
          "cannot be chosen for you. This step requires an explicit choice: re-run with "
          "HYPR_CONFIG_LANG=lua or HYPR_CONFIG_LANG=hyprlang (or --language <lua|hyprlang>).",
          file=out)


def detect_version(env=None):
    env = os.environ if env is None else env
    if env.get("HYPR_VERSION"):
        return env["HYPR_VERSION"]
    here = os.path.dirname(os.path.abspath(__file__))
    for cand in (f"{here}/detectversion.py",):
        if os.path.isfile(cand):
            from . import detectversion
            return detectversion.hypr_version() or "unknown"
    return "unknown"


class Resolution:
    def __init__(self, language=None, version="", source="", lines=None, rc=0):
        self.language, self.version, self.source = language, version, source
        self.lines, self.rc = lines or [], rc


def resolve(env=None, out=sys.stdout):
    """Print the resolution and return it. rc 3 means the caller must ASK."""
    env = os.environ if env is None else env
    choice = env.get("HYPR_CONFIG_LANG", "")
    if choice and choice not in ("lua", "hyprlang"):
        print(f"ERROR: HYPR_CONFIG_LANG must be `lua` or `hyprlang`, got: {choice}",
              file=sys.stderr)
        return Resolution(rc=2)

    version = detect_version(env)
    print(f"HYPR_VERSION={version}", file=out)

    if choice:
        lang, source = choice, "explicit"
    else:
        lang = for_version(version)
        if lang == "unknown":
            report_undecided(out)
            return Resolution(version=version, rc=3)
        source = "detected"

    print(f"CONFIG_LANGUAGE={lang}", file=out)
    print(f"CONFIG_LANGUAGE_SOURCE={source}", file=out)
    print(f"CONFIG_FILE={lang_file(lang)}", file=out)
    print(f"CONFIG_LANGUAGE_RANGE={lang_range(lang)}", file=out)
    return Resolution(language=lang, version=version, source=source)


def main(argv):
    env = dict(os.environ)
    args = argv[1:]
    i = 0
    while i < len(args):
        a = args[i]; i += 1
        if a == "--language":
            if i >= len(args):
                print("ERROR: --language needs a value", file=sys.stderr)
                return 2
            env["HYPR_CONFIG_LANG"] = args[i]; i += 1
        elif a == "--version":
            if i >= len(args):
                print("ERROR: --version needs a value", file=sys.stderr)
                return 2
            env["HYPR_VERSION"] = args[i]; i += 1
        elif a == "--range":
            if i >= len(args):
                print("ERROR: --range needs a language", file=sys.stderr)
                return 2
            r = lang_range(args[i])
            if not r:
                print(f"ERROR: unknown language: {args[i]}", file=sys.stderr)
                return 2
            print(r)
            return 0
        elif a in ("-h", "--help"):
            print(__doc__.strip())
            return 0
        else:
            print(f"ERROR: unknown argument: {a}", file=sys.stderr)
            return 2
    os.environ.update(env)
    return resolve(env).rc


if __name__ == "__main__":
    sys.exit(main(sys.argv))
